# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/kirby/Software/UnrealEngine5.6.1

TARGETS = \
	PuzzleGameNature-Android-DebugGame  \
	PuzzleGameNature-Android-Development  \
	PuzzleGameNature-Android-Shipping  \
	PuzzleGameNature-Linux-DebugGame  \
	PuzzleGameNature-Linux-Development  \
	PuzzleGameNature-Linux-Shipping  \
	PuzzleGameNature-LinuxArm64-DebugGame  \
	PuzzleGameNature-LinuxArm64-Development  \
	PuzzleGameNature-LinuxArm64-Shipping  \
	PuzzleGameNature \
	PuzzleGameNatureEditor-Linux-DebugGame  \
	PuzzleGameNatureEditor-Linux-Development  \
	PuzzleGameNatureEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend PuzzleGameNatureEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug PuzzleGameNatureEditor-Linux-Debug


PuzzleGameNature-Android-DebugGame:
	 $(BUILD) PuzzleGameNature Android DebugGame  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-Android-Development:
	 $(BUILD) PuzzleGameNature Android Development  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-Android-Shipping:
	 $(BUILD) PuzzleGameNature Android Shipping  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-Linux-DebugGame:
	 $(BUILD) PuzzleGameNature Linux DebugGame  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-Linux-Development:
	 $(BUILD) PuzzleGameNature Linux Development  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-Linux-Shipping:
	 $(BUILD) PuzzleGameNature Linux Shipping  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-LinuxArm64-DebugGame:
	 $(BUILD) PuzzleGameNature LinuxArm64 DebugGame  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-LinuxArm64-Development:
	 $(BUILD) PuzzleGameNature LinuxArm64 Development  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature-LinuxArm64-Shipping:
	 $(BUILD) PuzzleGameNature LinuxArm64 Shipping  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNature: PuzzleGameNature-Linux-Development

PuzzleGameNatureEditor-Linux-DebugGame:
	 $(BUILD) PuzzleGameNatureEditor Linux DebugGame  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNatureEditor-Linux-Development:
	 $(BUILD) PuzzleGameNatureEditor Linux Development  -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" $(ARGS)

PuzzleGameNatureEditor: PuzzleGameNatureEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/kirby/Documents/Unreal Projects/PuzzleGameNature/PuzzleGameNature.uproject" -Game 

.PHONY: $(TARGETS)
